"""PostgreSQL ORM model registry."""

from infra.persistence.postgres.models.auth import AuthSession, AuthUser
from infra.persistence.postgres.models.build import (
    ArtifactVersion,
    BuildStage,
    CollectionActiveBuild,
    CollectionBuild,
    Task,
)
from infra.persistence.postgres.models.comparison import (
    CollectionComparableResultRecord,
    ComparableResultRecord,
    ComparisonBuild,
    PairwiseComparisonRelationRecord,
)
from infra.persistence.postgres.models.collection import (
    Collection,
    CollectionFile,
    CollectionHandoff,
    CollectionImport,
    CollectionImportDocument,
    StoredObject,
)
from infra.persistence.postgres.models.document import (
    CollectionDocument,
    Document,
    DocumentVersion,
)
from infra.persistence.postgres.models.evaluation import (
    ResearchUnderstandingCurationRecord,
    ResearchUnderstandingFeedbackRecord,
)
from infra.persistence.postgres.models.migration import ObjectiveIdentityMigration
from infra.persistence.postgres.models.paper_fact import (
    PaperFactBaselineReference,
    PaperFactBuild,
    PaperFactCharacterizationObservation,
    PaperFactDocumentProfile,
    PaperFactEvidenceAnchor,
    PaperFactMeasurementResult,
    PaperFactMethod,
    PaperFactSampleVariant,
    PaperFactStructureFeature,
    PaperFactTestCondition,
)
from infra.persistence.postgres.models.objective import (
    ObjectiveBuild,
    ObjectiveContextRecord,
    ObjectiveEvidenceRouteRecord,
    ObjectiveEvidenceUnitRecord,
    ObjectiveLogicChainRecord,
    ObjectivePaperFrameRecord,
    ObjectivePaperSkim,
    ObjectiveResearchRecord,
)
from infra.persistence.postgres.models.objective_workspace import (
    ObjectiveExperimentPlan,
    ObjectiveMessage,
    ObjectiveSession,
)
from infra.persistence.postgres.models.source import (
    SourceBlock,
    SourceBlockTextUnit,
    SourceDocument,
    SourceFigure,
    SourceReferenceCandidate,
    SourceReferenceEntry,
    SourceReferenceMention,
    SourceReferenceResolution,
    SourceTable,
    SourceTableCell,
    SourceTableRow,
    SourceTextUnit,
    SourceTextUnitDocument,
)
from infra.persistence.postgres.models.understanding import (
    ResearchClaimRecord,
    ResearchContextRecord,
    ResearchEvidenceRefRecord,
    ResearchFindingRecord,
    ResearchRelationRecord,
    ResearchUnderstandingRecord,
)

__all__ = [
    "ArtifactVersion",
    "AuthSession",
    "AuthUser",
    "BuildStage",
    "Collection",
    "CollectionActiveBuild",
    "CollectionComparableResultRecord",
    "CollectionBuild",
    "ComparableResultRecord",
    "ComparisonBuild",
    "CollectionDocument",
    "CollectionFile",
    "CollectionHandoff",
    "CollectionImport",
    "CollectionImportDocument",
    "Document",
    "DocumentVersion",
    "ObjectiveBuild",
    "ObjectiveExperimentPlan",
    "ObjectiveIdentityMigration",
    "ObjectiveMessage",
    "ObjectiveContextRecord",
    "ObjectiveEvidenceRouteRecord",
    "ObjectiveEvidenceUnitRecord",
    "ObjectiveLogicChainRecord",
    "ObjectivePaperFrameRecord",
    "ObjectivePaperSkim",
    "ObjectiveResearchRecord",
    "ObjectiveSession",
    "PairwiseComparisonRelationRecord",
    "PaperFactBaselineReference",
    "PaperFactBuild",
    "PaperFactCharacterizationObservation",
    "PaperFactDocumentProfile",
    "PaperFactEvidenceAnchor",
    "PaperFactMeasurementResult",
    "PaperFactMethod",
    "PaperFactSampleVariant",
    "PaperFactStructureFeature",
    "PaperFactTestCondition",
    "ResearchClaimRecord",
    "ResearchContextRecord",
    "ResearchEvidenceRefRecord",
    "ResearchFindingRecord",
    "ResearchRelationRecord",
    "ResearchUnderstandingCurationRecord",
    "ResearchUnderstandingFeedbackRecord",
    "ResearchUnderstandingRecord",
    "StoredObject",
    "SourceBlock",
    "SourceBlockTextUnit",
    "SourceDocument",
    "SourceFigure",
    "SourceReferenceCandidate",
    "SourceReferenceEntry",
    "SourceReferenceMention",
    "SourceReferenceResolution",
    "SourceTable",
    "SourceTableCell",
    "SourceTableRow",
    "SourceTextUnit",
    "SourceTextUnitDocument",
    "Task",
]
