from __future__ import annotations

from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
import pytest
from sqlalchemy import Column, Integer, Table, create_engine, inspect
from sqlalchemy.engine import URL

from infra.persistence.postgres.base import Base


BACKEND_ROOT = Path(__file__).resolve().parents[3]
BASELINE_REVISION = "20260718_0001"


def test_empty_database_upgrades_checks_downgrades_and_upgrades_again(
    tmp_path,
) -> None:
    engine = create_engine(
        URL.create(
            "sqlite+pysqlite",
            database=str(tmp_path / "migration.sqlite"),
        )
    )
    config = Config(str(BACKEND_ROOT / "alembic.ini"))

    assert ScriptDirectory.from_config(config).get_current_head() == BASELINE_REVISION

    try:
        with engine.begin() as connection:
            config.attributes["connection"] = connection

            assert MigrationContext.configure(connection).get_current_revision() is None

            command.upgrade(config, "head")

            assert (
                MigrationContext.configure(connection).get_current_revision()
                == BASELINE_REVISION
            )
            assert inspect(connection).get_table_names() == ["alembic_version"]
            command.check(config)

            command.downgrade(config, "base")

            assert MigrationContext.configure(connection).get_current_revision() is None

            command.upgrade(config, "head")

            assert (
                MigrationContext.configure(connection).get_current_revision()
                == BASELINE_REVISION
            )
    finally:
        engine.dispose()


def test_alembic_check_rejects_model_drift(tmp_path) -> None:
    engine = create_engine(
        URL.create(
            "sqlite+pysqlite",
            database=str(tmp_path / "drift.sqlite"),
        )
    )
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    drift_table = Table(
        "unmigrated_example",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )

    assert drift_table.primary_key.name == "pk_unmigrated_example"

    try:
        with engine.begin() as connection:
            config.attributes["connection"] = connection
            command.upgrade(config, "head")

            with pytest.raises(
                AutogenerateDiffsDetected,
                match="New upgrade operations detected",
            ):
                command.check(config)
    finally:
        Base.metadata.remove(drift_table)
        engine.dispose()
