from __future__ import annotations

import os
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
import pytest
from sqlalchemy import Column, Integer, Table, create_engine, inspect, text
from sqlalchemy.engine import URL, make_url

from infra.persistence.postgres.base import Base


BACKEND_ROOT = Path(__file__).resolve().parents[3]
HEAD_REVISION = "20260719_0006"


def test_empty_database_upgrades_checks_downgrades_and_upgrades_again(
    tmp_path,
) -> None:
    engine = create_engine(
        URL.create(
            "sqlite+pysqlite",
            database=str(tmp_path / "migration.sqlite"),
        )
    )
    config = Config(str(BACKEND_ROOT / "alembic.ini"))

    assert ScriptDirectory.from_config(config).get_current_head() == HEAD_REVISION

    try:
        with engine.begin() as connection:
            config.attributes["connection"] = connection

            assert MigrationContext.configure(connection).get_current_revision() is None

            command.upgrade(config, "head")

            assert (
                MigrationContext.configure(connection).get_current_revision()
                == HEAD_REVISION
            )
            assert inspect(connection).get_table_names() == [
                "alembic_version",
                "artifact_versions",
                "auth_sessions",
                "auth_users",
                "build_stages",
                "collection_active_builds",
                "collection_builds",
                "collection_documents",
                "collection_files",
                "collection_handoffs",
                "collection_import_documents",
                "collection_imports",
                "collections",
                "document_versions",
                "documents",
                "stored_objects",
                "tasks",
            ]
            command.check(config)

            command.downgrade(config, "base")

            assert MigrationContext.configure(connection).get_current_revision() is None
            assert inspect(connection).get_table_names() == ["alembic_version"]

            command.upgrade(config, "head")

            assert (
                MigrationContext.configure(connection).get_current_revision()
                == HEAD_REVISION
            )
    finally:
        engine.dispose()


def test_postgresql_migration_lifecycle_matches_models() -> None:
    database_url = os.getenv("LENS_TEST_DATABASE_URL")
    if not database_url:
        pytest.skip("LENS_TEST_DATABASE_URL is not configured")
    url = make_url(database_url)
    if url.drivername != "postgresql+psycopg" or not str(url.database).endswith(
        "_test"
    ):
        pytest.fail(
            "LENS_TEST_DATABASE_URL must use postgresql+psycopg and a *_test database"
        )

    engine = create_engine(url)
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    try:
        with engine.begin() as connection:
            config.attributes["connection"] = connection
            command.downgrade(config, "base")
            assert MigrationContext.configure(connection).get_current_revision() is None

            command.upgrade(config, "head")
            assert (
                MigrationContext.configure(connection).get_current_revision()
                == HEAD_REVISION
            )
            assert set(inspect(connection).get_table_names()) == {
                "alembic_version",
                "auth_sessions",
                "auth_users",
                "artifact_versions",
                "build_stages",
                "collection_active_builds",
                "collection_builds",
                "collection_documents",
                "collection_files",
                "collection_handoffs",
                "collection_import_documents",
                "collection_imports",
                "collections",
                "document_versions",
                "documents",
                "stored_objects",
                "tasks",
            }
            command.check(config)

            command.downgrade(config, "base")
            assert MigrationContext.configure(connection).get_current_revision() is None
            assert inspect(connection).get_table_names() == ["alembic_version"]

            command.upgrade(config, "head")
            assert (
                MigrationContext.configure(connection).get_current_revision()
                == HEAD_REVISION
            )
    finally:
        with engine.begin() as connection:
            config.attributes["connection"] = connection
            command.downgrade(config, "base")
        engine.dispose()


def test_document_version_migration_backfills_existing_file_provenance(
    tmp_path,
) -> None:
    engine = create_engine(
        URL.create(
            "sqlite+pysqlite",
            database=str(tmp_path / "document-backfill.sqlite"),
        )
    )
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    created_at = "2026-07-19 09:00:00+00:00"
    try:
        with engine.begin() as connection:
            config.attributes["connection"] = connection
            command.upgrade(config, "20260719_0005")
            connection.execute(
                text(
                    """
                    INSERT INTO auth_users (
                        user_id, email, display_name, password_hash, created_at
                    ) VALUES (
                        'user_backfill', 'backfill@example.com', NULL,
                        'synthetic-password-hash', :created_at
                    )
                    """
                ),
                {"created_at": created_at},
            )
            for collection_id, paper_count in (
                ("col_backfill_a", 2),
                ("col_backfill_b", 1),
            ):
                connection.execute(
                    text(
                        """
                        INSERT INTO collections (
                            collection_id, owner_user_id, name, description,
                            status, paper_count, created_at, updated_at
                        ) VALUES (
                            :collection_id, 'user_backfill', :collection_id, NULL,
                            'ready', :paper_count, :created_at, :created_at
                        )
                        """
                    ),
                    {
                        "collection_id": collection_id,
                        "paper_count": paper_count,
                        "created_at": created_at,
                    },
                )
            for index, collection_id in enumerate(
                ("col_backfill_a", "col_backfill_a", "col_backfill_b")
            ):
                object_id = f"obj_backfill_{index}"
                file_id = f"file_backfill_{index}"
                connection.execute(
                    text(
                        """
                        INSERT INTO stored_objects (
                            object_id, object_kind, storage_key, sha256,
                            size_bytes, media_type, created_at
                        ) VALUES (
                            :object_id, 'source_input', :storage_key, :sha256,
                            42, 'application/pdf', :created_at
                        )
                        """
                    ),
                    {
                        "object_id": object_id,
                        "storage_key": f"{collection_id}/input/{file_id}.pdf",
                        "sha256": "a" * 64,
                        "created_at": created_at,
                    },
                )
                connection.execute(
                    text(
                        """
                        INSERT INTO collection_files (
                            file_id, collection_id, object_id, original_filename,
                            stored_filename, status, document_id, file_order,
                            created_at
                        ) VALUES (
                            :file_id, :collection_id, :object_id, :filename,
                            :filename, 'stored', NULL, :file_order, :created_at
                        )
                        """
                    ),
                    {
                        "file_id": file_id,
                        "collection_id": collection_id,
                        "object_id": object_id,
                        "filename": f"{file_id}.pdf",
                        "file_order": index if collection_id == "col_backfill_a" else 0,
                        "created_at": created_at,
                    },
                )

            command.upgrade(config, "head")

            assert connection.scalar(text("SELECT count(*) FROM documents")) == 1
            assert (
                connection.scalar(text("SELECT count(*) FROM document_versions")) == 1
            )
            assert (
                connection.scalar(text("SELECT count(*) FROM collection_documents"))
                == 2
            )
            assert (
                connection.scalar(
                    text(
                        "SELECT count(DISTINCT document_version_id) FROM stored_objects"
                    )
                )
                == 1
            )
            assert (
                connection.scalar(
                    text(
                        "SELECT count(DISTINCT collection_document_id) "
                        "FROM collection_files"
                    )
                )
                == 2
            )
            assert {
                collection_id: paper_count
                for collection_id, paper_count in connection.execute(
                    text(
                        "SELECT collection_id, paper_count FROM collections "
                        "ORDER BY collection_id"
                    )
                )
            } == {"col_backfill_a": 1, "col_backfill_b": 1}

            command.downgrade(config, "20260719_0005")

            assert "documents" not in inspect(connection).get_table_names()
            assert "document_version_id" not in {
                column["name"]
                for column in inspect(connection).get_columns("stored_objects")
            }
            assert {
                collection_id: paper_count
                for collection_id, paper_count in connection.execute(
                    text(
                        "SELECT collection_id, paper_count FROM collections "
                        "ORDER BY collection_id"
                    )
                )
            } == {"col_backfill_a": 2, "col_backfill_b": 1}

            command.upgrade(config, "head")

            assert connection.scalar(text("SELECT count(*) FROM documents")) == 1
            assert (
                connection.scalar(text("SELECT count(*) FROM collection_documents"))
                == 2
            )
    finally:
        engine.dispose()


def test_alembic_check_rejects_model_drift(tmp_path) -> None:
    engine = create_engine(
        URL.create(
            "sqlite+pysqlite",
            database=str(tmp_path / "drift.sqlite"),
        )
    )
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    drift_table = Table(
        "unmigrated_example",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )

    assert drift_table.primary_key.name == "pk_unmigrated_example"

    try:
        with engine.begin() as connection:
            config.attributes["connection"] = connection
            command.upgrade(config, "head")

            with pytest.raises(
                AutogenerateDiffsDetected,
                match="New upgrade operations detected",
            ):
                command.check(config)
    finally:
        Base.metadata.remove(drift_table)
        engine.dispose()
