"""Shared domain enums and value semantics."""

from domain.shared.enums import (
    COMPARABILITY_STATUS_COMPARABLE,
    COMPARABILITY_STATUS_INSUFFICIENT,
    COMPARABILITY_STATUS_LIMITED,
    COMPARABILITY_STATUS_NOT_COMPARABLE,
    DOC_TYPE_EXPERIMENTAL,
    DOC_TYPE_MIXED,
    DOC_TYPE_REVIEW,
    DOC_TYPE_UNCERTAIN,
    EPISTEMIC_DIRECTLY_OBSERVED,
    EPISTEMIC_INFERRED_FROM_CHARACTERIZATION,
    EPISTEMIC_INFERRED_WITH_LOW_CONFIDENCE,
    EPISTEMIC_NORMALIZED_FROM_EVIDENCE,
    EPISTEMIC_UNRESOLVED,
    TRACEABILITY_STATUS_DIRECT,
    TRACEABILITY_STATUS_MISSING,
    TRACEABILITY_STATUS_PARTIAL,
)
from domain.shared.record_normalization import normalize_record_value

__all__ = [
    "COMPARABILITY_STATUS_COMPARABLE",
    "COMPARABILITY_STATUS_INSUFFICIENT",
    "COMPARABILITY_STATUS_LIMITED",
    "COMPARABILITY_STATUS_NOT_COMPARABLE",
    "DOC_TYPE_EXPERIMENTAL",
    "DOC_TYPE_MIXED",
    "DOC_TYPE_REVIEW",
    "DOC_TYPE_UNCERTAIN",
    "EPISTEMIC_DIRECTLY_OBSERVED",
    "EPISTEMIC_INFERRED_FROM_CHARACTERIZATION",
    "EPISTEMIC_INFERRED_WITH_LOW_CONFIDENCE",
    "EPISTEMIC_NORMALIZED_FROM_EVIDENCE",
    "EPISTEMIC_UNRESOLVED",
    "TRACEABILITY_STATUS_DIRECT",
    "TRACEABILITY_STATUS_MISSING",
    "TRACEABILITY_STATUS_PARTIAL",
    "normalize_record_value",
]
