"""Core domain models and judgment rules."""

from domain.core.comparison import (
    COMPARABLE_RESULT_NORMALIZATION_VERSION,
    COMPARISON_ROW_PROJECTION_VERSION,
    CollectionComparableResult,
    ComparableResult,
    ComparisonAssessment,
    ComparisonAxis,
    ComparisonRowRecord,
    ContextBinding,
    EvidenceTrace,
    NormalizedComparisonContext,
    ResultValue,
    SCALAR_LIKE_RESULT_TYPES,
    build_comparable_result_id,
    build_comparison_row_id,
    evaluate_comparison_assessment,
)
from domain.core.comparison_assembly import (
    COLLECTION_COMPARABLE_RESULT_COLUMNS,
    COMPARABLE_RESULT_COLUMNS,
    ComparableResultAssembler,
    ComparisonInputRecords,
    ComparisonSemanticRecords,
)
from domain.core.comparison_projection import (
    COMPARISON_ROW_COLUMNS,
    ComparisonProjectionRecords,
    ComparisonRowProjector,
)
from domain.core.document_profile import (
    DocumentProfile,
    DocumentProfileSummary,
    summarize_document_profile_collection,
)
from domain.core.evidence_backbone import (
    BaselineReference,
    CORE_NEUTRAL_DOMAIN_PROFILE,
    CharacterizationObservation,
    EvidenceAnchor,
    MeasurementResult,
    MethodFact,
    SampleVariant,
    StructureFeature,
    TestCondition,
)
from domain.core.fact_store import CoreFactSet
from domain.core.research_objective import (
    EVIDENCE_ROUTE_ROLE_VALUES,
    EvidenceRoute,
    ObjectivePaperFrame,
    PAPER_RELEVANCE_VALUES,
    PAPER_ROLE_VALUES,
    PaperSkim,
    ResearchObjective,
    SOURCE_KIND_VALUES,
    build_research_objective_id,
    is_question_shaped_objective,
    normalize_objective_confidence,
    normalize_objective_terms,
)

__all__ = [
    "BaselineReference",
    "COMPARABLE_RESULT_NORMALIZATION_VERSION",
    "COLLECTION_COMPARABLE_RESULT_COLUMNS",
    "COMPARABLE_RESULT_COLUMNS",
    "COMPARISON_ROW_COLUMNS",
    "COMPARISON_ROW_PROJECTION_VERSION",
    "CORE_NEUTRAL_DOMAIN_PROFILE",
    "CharacterizationObservation",
    "CollectionComparableResult",
    "ComparableResult",
    "ComparableResultAssembler",
    "ComparisonAssessment",
    "ComparisonAxis",
    "ComparisonInputRecords",
    "ComparisonProjectionRecords",
    "ComparisonRowRecord",
    "ComparisonRowProjector",
    "ComparisonSemanticRecords",
    "ContextBinding",
    "CoreFactSet",
    "DocumentProfile",
    "DocumentProfileSummary",
    "EVIDENCE_ROUTE_ROLE_VALUES",
    "EvidenceTrace",
    "EvidenceAnchor",
    "EvidenceRoute",
    "MeasurementResult",
    "MethodFact",
    "NormalizedComparisonContext",
    "ObjectivePaperFrame",
    "PAPER_RELEVANCE_VALUES",
    "PAPER_ROLE_VALUES",
    "PaperSkim",
    "ResearchObjective",
    "ResultValue",
    "SCALAR_LIKE_RESULT_TYPES",
    "SOURCE_KIND_VALUES",
    "SampleVariant",
    "StructureFeature",
    "TestCondition",
    "build_comparable_result_id",
    "build_comparison_row_id",
    "build_research_objective_id",
    "evaluate_comparison_assessment",
    "is_question_shaped_objective",
    "normalize_objective_confidence",
    "normalize_objective_terms",
    "summarize_document_profile_collection",
]
