"""Add build-versioned paper facts.

Revision ID: 20260719_0009
Revises: 20260719_0008
Create Date: 2026-07-19 22:24:08.079888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260719_0009"
down_revision: Union[str, Sequence[str], None] = "20260719_0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_fact_builds",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("paper_facts_ready", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id"],
            ["collection_builds.collection_id", "collection_builds.build_id"],
            name="fk_paper_fact_builds_collection_build",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("build_id", name=op.f("pk_paper_fact_builds")),
    )
    op.create_index(
        op.f("ix_paper_fact_builds_collection_id"),
        "paper_fact_builds",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_document_profiles",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("profile_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("source_filename", sa.Text(), nullable=True),
        sa.Column("doc_type", sa.String(length=32), nullable=False),
        sa.Column(
            "parsing_warnings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_paper_fact_document_profiles_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_document_profiles_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_document_profiles_document_version_id_document_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "source_document_id",
            name=op.f("pk_paper_fact_document_profiles"),
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_document_profiles_collection_id"),
        "paper_fact_document_profiles",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_fact_document_profiles_document_version_id"),
        "paper_fact_document_profiles",
        ["document_version_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_evidence_anchors",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("anchor_order", sa.Integer(), nullable=False),
        sa.Column("locator_type", sa.String(length=64), nullable=False),
        sa.Column("locator_confidence", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("section_id", sa.Text(), nullable=True),
        sa.Column(
            "char_range_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "bbox_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("deep_link", sa.Text(), nullable=True),
        sa.Column("block_id", sa.String(length=128), nullable=True),
        sa.Column("snippet_id", sa.String(length=128), nullable=True),
        sa.Column("figure_or_table", sa.String(length=128), nullable=True),
        sa.Column("quote_span", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "page IS NULL OR page >= 0",
            name=op.f("ck_paper_fact_evidence_anchors_page_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_evidence_anchors_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_evidence_anchors_document_version_id_document_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "anchor_id", name=op.f("pk_paper_fact_evidence_anchors")
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_evidence_anchors_collection_id"),
        "paper_fact_evidence_anchors",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_fact_evidence_anchors_document_version_id"),
        "paper_fact_evidence_anchors",
        ["document_version_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_methods",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("method_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_order", sa.Integer(), nullable=False),
        sa.Column("domain_profile", sa.String(length=64), nullable=False),
        sa.Column("method_role", sa.String(length=128), nullable=False),
        sa.Column("method_name", sa.Text(), nullable=False),
        sa.Column(
            "method_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_paper_fact_methods_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_methods_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f("fk_paper_fact_methods_document_version_id_document_versions"),
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "method_id", name=op.f("pk_paper_fact_methods")
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_methods_collection_id"),
        "paper_fact_methods",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_sample_variants",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("variant_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_order", sa.Integer(), nullable=False),
        sa.Column("domain_profile", sa.String(length=64), nullable=False),
        sa.Column("variant_label", sa.Text(), nullable=False),
        sa.Column(
            "host_material_system",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("composition", sa.Text(), nullable=True),
        sa.Column("variable_axis_type", sa.String(length=128), nullable=True),
        sa.Column(
            "variable_value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "process_context",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "profile_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_paper_fact_sample_variants_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_sample_variants_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_sample_variants_document_version_id_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "variant_id", name=op.f("pk_paper_fact_sample_variants")
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_sample_variants_collection_id"),
        "paper_fact_sample_variants",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_test_conditions",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("test_condition_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_order", sa.Integer(), nullable=False),
        sa.Column("domain_profile", sa.String(length=64), nullable=False),
        sa.Column("property_type", sa.String(length=128), nullable=False),
        sa.Column("template_type", sa.String(length=128), nullable=False),
        sa.Column("scope_level", sa.String(length=64), nullable=False),
        sa.Column(
            "condition_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("condition_completeness", sa.String(length=64), nullable=False),
        sa.Column(
            "missing_fields",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_paper_fact_test_conditions_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_test_conditions_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_test_conditions_document_version_id_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "test_condition_id", name=op.f("pk_paper_fact_test_conditions")
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_test_conditions_collection_id"),
        "paper_fact_test_conditions",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_baseline_references",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("baseline_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_order", sa.Integer(), nullable=False),
        sa.Column("domain_profile", sa.String(length=64), nullable=False),
        sa.Column("variant_id", sa.String(length=128), nullable=True),
        sa.Column("baseline_type", sa.String(length=64), nullable=False),
        sa.Column("baseline_label", sa.Text(), nullable=False),
        sa.Column("baseline_scope", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_paper_fact_baseline_references_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "variant_id"],
            [
                "paper_fact_sample_variants.build_id",
                "paper_fact_sample_variants.variant_id",
            ],
            name="fk_paper_fact_baselines_variant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_baselines_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_baseline_references_document_version_id_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "baseline_id", name=op.f("pk_paper_fact_baseline_references")
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_baseline_references_collection_id"),
        "paper_fact_baseline_references",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_characterization_observations",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("observation_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_order", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.String(length=128), nullable=True),
        sa.Column("characterization_type", sa.String(length=128), nullable=False),
        sa.Column("observation_text", sa.Text(), nullable=False),
        sa.Column(
            "observed_value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("observed_unit", sa.String(length=64), nullable=True),
        sa.Column(
            "condition_context",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_paper_fact_characterization_observations_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "variant_id"],
            [
                "paper_fact_sample_variants.build_id",
                "paper_fact_sample_variants.variant_id",
            ],
            name="fk_paper_fact_observations_variant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_observations_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_characterization_observations_document_version_id_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "observation_id",
            name=op.f("pk_paper_fact_characterization_observations"),
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_characterization_observations_collection_id"),
        "paper_fact_characterization_observations",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_condition_evidence_anchors",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("test_condition_id", sa.String(length=128), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "anchor_id"],
            [
                "paper_fact_evidence_anchors.build_id",
                "paper_fact_evidence_anchors.anchor_id",
            ],
            name=op.f(
                "fk_paper_fact_condition_evidence_anchors_build_id_paper_fact_evidence_anchors"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "test_condition_id"],
            [
                "paper_fact_test_conditions.build_id",
                "paper_fact_test_conditions.test_condition_id",
            ],
            name=op.f(
                "fk_paper_fact_condition_evidence_anchors_build_id_paper_fact_test_conditions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "test_condition_id",
            "anchor_id",
            name=op.f("pk_paper_fact_condition_evidence_anchors"),
        ),
    )
    op.create_table(
        "paper_fact_method_evidence_anchors",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("method_id", sa.String(length=128), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "anchor_id"],
            [
                "paper_fact_evidence_anchors.build_id",
                "paper_fact_evidence_anchors.anchor_id",
            ],
            name=op.f(
                "fk_paper_fact_method_evidence_anchors_build_id_paper_fact_evidence_anchors"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "method_id"],
            ["paper_fact_methods.build_id", "paper_fact_methods.method_id"],
            name=op.f(
                "fk_paper_fact_method_evidence_anchors_build_id_paper_fact_methods"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "method_id",
            "anchor_id",
            name=op.f("pk_paper_fact_method_evidence_anchors"),
        ),
    )
    op.create_table(
        "paper_fact_structure_features",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("feature_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_order", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.String(length=128), nullable=True),
        sa.Column("feature_type", sa.String(length=128), nullable=False),
        sa.Column(
            "feature_value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("feature_unit", sa.String(length=64), nullable=True),
        sa.Column("qualitative_descriptor", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_paper_fact_structure_features_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "variant_id"],
            [
                "paper_fact_sample_variants.build_id",
                "paper_fact_sample_variants.variant_id",
            ],
            name="fk_paper_fact_features_variant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_features_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_structure_features_document_version_id_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "feature_id", name=op.f("pk_paper_fact_structure_features")
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_structure_features_collection_id"),
        "paper_fact_structure_features",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_variant_evidence_anchors",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("variant_id", sa.String(length=128), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "anchor_id"],
            [
                "paper_fact_evidence_anchors.build_id",
                "paper_fact_evidence_anchors.anchor_id",
            ],
            name=op.f(
                "fk_paper_fact_variant_evidence_anchors_build_id_paper_fact_evidence_anchors"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "variant_id"],
            [
                "paper_fact_sample_variants.build_id",
                "paper_fact_sample_variants.variant_id",
            ],
            name=op.f(
                "fk_paper_fact_variant_evidence_anchors_build_id_paper_fact_sample_variants"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "variant_id",
            "anchor_id",
            name=op.f("pk_paper_fact_variant_evidence_anchors"),
        ),
    )
    op.create_table(
        "paper_fact_baseline_evidence_anchors",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("baseline_id", sa.String(length=128), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "anchor_id"],
            [
                "paper_fact_evidence_anchors.build_id",
                "paper_fact_evidence_anchors.anchor_id",
            ],
            name=op.f(
                "fk_paper_fact_baseline_evidence_anchors_build_id_paper_fact_evidence_anchors"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "baseline_id"],
            [
                "paper_fact_baseline_references.build_id",
                "paper_fact_baseline_references.baseline_id",
            ],
            name=op.f(
                "fk_paper_fact_baseline_evidence_anchors_build_id_paper_fact_baseline_references"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "baseline_id",
            "anchor_id",
            name=op.f("pk_paper_fact_baseline_evidence_anchors"),
        ),
    )
    op.create_table(
        "paper_fact_feature_observations",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("feature_id", sa.String(length=128), nullable=False),
        sa.Column("observation_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "feature_id"],
            [
                "paper_fact_structure_features.build_id",
                "paper_fact_structure_features.feature_id",
            ],
            name=op.f(
                "fk_paper_fact_feature_observations_build_id_paper_fact_structure_features"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "observation_id"],
            [
                "paper_fact_characterization_observations.build_id",
                "paper_fact_characterization_observations.observation_id",
            ],
            name=op.f(
                "fk_paper_fact_feature_observations_build_id_paper_fact_characterization_observations"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "feature_id",
            "observation_id",
            name=op.f("pk_paper_fact_feature_observations"),
        ),
    )
    op.create_table(
        "paper_fact_measurement_results",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("result_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("document_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_order", sa.Integer(), nullable=False),
        sa.Column("domain_profile", sa.String(length=64), nullable=False),
        sa.Column("variant_id", sa.String(length=128), nullable=True),
        sa.Column("property_normalized", sa.String(length=128), nullable=False),
        sa.Column("result_type", sa.String(length=64), nullable=False),
        sa.Column("claim_scope", sa.String(length=64), nullable=False),
        sa.Column(
            "value_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("test_condition_id", sa.String(length=128), nullable=True),
        sa.Column("baseline_id", sa.String(length=128), nullable=True),
        sa.Column("traceability_status", sa.String(length=64), nullable=False),
        sa.Column("result_source_type", sa.String(length=64), nullable=False),
        sa.Column("epistemic_status", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "baseline_id"],
            [
                "paper_fact_baseline_references.build_id",
                "paper_fact_baseline_references.baseline_id",
            ],
            name="fk_paper_fact_results_baseline",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "test_condition_id"],
            [
                "paper_fact_test_conditions.build_id",
                "paper_fact_test_conditions.test_condition_id",
            ],
            name="fk_paper_fact_results_condition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "variant_id"],
            [
                "paper_fact_sample_variants.build_id",
                "paper_fact_sample_variants.variant_id",
            ],
            name="fk_paper_fact_results_variant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_paper_fact_results_source_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.document_version_id"],
            name=op.f(
                "fk_paper_fact_measurement_results_document_version_id_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "result_id", name=op.f("pk_paper_fact_measurement_results")
        ),
    )
    op.create_index(
        op.f("ix_paper_fact_measurement_results_collection_id"),
        "paper_fact_measurement_results",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "paper_fact_observation_evidence_anchors",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("observation_id", sa.String(length=128), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "anchor_id"],
            [
                "paper_fact_evidence_anchors.build_id",
                "paper_fact_evidence_anchors.anchor_id",
            ],
            name=op.f(
                "fk_paper_fact_observation_evidence_anchors_build_id_paper_fact_evidence_anchors"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "observation_id"],
            [
                "paper_fact_characterization_observations.build_id",
                "paper_fact_characterization_observations.observation_id",
            ],
            name=op.f(
                "fk_paper_fact_observation_evidence_anchors_build_id_paper_fact_characterization_observations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "observation_id",
            "anchor_id",
            name=op.f("pk_paper_fact_observation_evidence_anchors"),
        ),
    )
    op.create_table(
        "paper_fact_variant_structure_features",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("variant_id", sa.String(length=128), nullable=False),
        sa.Column("feature_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "feature_id"],
            [
                "paper_fact_structure_features.build_id",
                "paper_fact_structure_features.feature_id",
            ],
            name=op.f(
                "fk_paper_fact_variant_structure_features_build_id_paper_fact_structure_features"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "variant_id"],
            [
                "paper_fact_sample_variants.build_id",
                "paper_fact_sample_variants.variant_id",
            ],
            name=op.f(
                "fk_paper_fact_variant_structure_features_build_id_paper_fact_sample_variants"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "variant_id",
            "feature_id",
            name=op.f("pk_paper_fact_variant_structure_features"),
        ),
    )
    op.create_table(
        "paper_fact_result_evidence_anchors",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("result_id", sa.String(length=128), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "anchor_id"],
            [
                "paper_fact_evidence_anchors.build_id",
                "paper_fact_evidence_anchors.anchor_id",
            ],
            name=op.f(
                "fk_paper_fact_result_evidence_anchors_build_id_paper_fact_evidence_anchors"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "result_id"],
            [
                "paper_fact_measurement_results.build_id",
                "paper_fact_measurement_results.result_id",
            ],
            name=op.f(
                "fk_paper_fact_result_evidence_anchors_build_id_paper_fact_measurement_results"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "result_id",
            "anchor_id",
            name=op.f("pk_paper_fact_result_evidence_anchors"),
        ),
    )
    op.create_table(
        "paper_fact_result_observations",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("result_id", sa.String(length=128), nullable=False),
        sa.Column("observation_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "observation_id"],
            [
                "paper_fact_characterization_observations.build_id",
                "paper_fact_characterization_observations.observation_id",
            ],
            name=op.f(
                "fk_paper_fact_result_observations_build_id_paper_fact_characterization_observations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "result_id"],
            [
                "paper_fact_measurement_results.build_id",
                "paper_fact_measurement_results.result_id",
            ],
            name=op.f(
                "fk_paper_fact_result_observations_build_id_paper_fact_measurement_results"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "result_id",
            "observation_id",
            name=op.f("pk_paper_fact_result_observations"),
        ),
    )
    op.create_table(
        "paper_fact_result_structure_features",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("result_id", sa.String(length=128), nullable=False),
        sa.Column("feature_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "feature_id"],
            [
                "paper_fact_structure_features.build_id",
                "paper_fact_structure_features.feature_id",
            ],
            name=op.f(
                "fk_paper_fact_result_structure_features_build_id_paper_fact_structure_features"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "result_id"],
            [
                "paper_fact_measurement_results.build_id",
                "paper_fact_measurement_results.result_id",
            ],
            name=op.f(
                "fk_paper_fact_result_structure_features_build_id_paper_fact_measurement_results"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "result_id",
            "feature_id",
            name=op.f("pk_paper_fact_result_structure_features"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_fact_result_structure_features")
    op.drop_table("paper_fact_result_observations")
    op.drop_table("paper_fact_result_evidence_anchors")
    op.drop_table("paper_fact_variant_structure_features")
    op.drop_table("paper_fact_observation_evidence_anchors")
    op.drop_index(
        op.f("ix_paper_fact_measurement_results_collection_id"),
        table_name="paper_fact_measurement_results",
    )
    op.drop_table("paper_fact_measurement_results")
    op.drop_table("paper_fact_feature_observations")
    op.drop_table("paper_fact_baseline_evidence_anchors")
    op.drop_table("paper_fact_variant_evidence_anchors")
    op.drop_index(
        op.f("ix_paper_fact_structure_features_collection_id"),
        table_name="paper_fact_structure_features",
    )
    op.drop_table("paper_fact_structure_features")
    op.drop_table("paper_fact_method_evidence_anchors")
    op.drop_table("paper_fact_condition_evidence_anchors")
    op.drop_index(
        op.f("ix_paper_fact_characterization_observations_collection_id"),
        table_name="paper_fact_characterization_observations",
    )
    op.drop_table("paper_fact_characterization_observations")
    op.drop_index(
        op.f("ix_paper_fact_baseline_references_collection_id"),
        table_name="paper_fact_baseline_references",
    )
    op.drop_table("paper_fact_baseline_references")
    op.drop_index(
        op.f("ix_paper_fact_test_conditions_collection_id"),
        table_name="paper_fact_test_conditions",
    )
    op.drop_table("paper_fact_test_conditions")
    op.drop_index(
        op.f("ix_paper_fact_sample_variants_collection_id"),
        table_name="paper_fact_sample_variants",
    )
    op.drop_table("paper_fact_sample_variants")
    op.drop_index(
        op.f("ix_paper_fact_methods_collection_id"), table_name="paper_fact_methods"
    )
    op.drop_table("paper_fact_methods")
    op.drop_index(
        op.f("ix_paper_fact_evidence_anchors_document_version_id"),
        table_name="paper_fact_evidence_anchors",
    )
    op.drop_index(
        op.f("ix_paper_fact_evidence_anchors_collection_id"),
        table_name="paper_fact_evidence_anchors",
    )
    op.drop_table("paper_fact_evidence_anchors")
    op.drop_index(
        op.f("ix_paper_fact_document_profiles_document_version_id"),
        table_name="paper_fact_document_profiles",
    )
    op.drop_index(
        op.f("ix_paper_fact_document_profiles_collection_id"),
        table_name="paper_fact_document_profiles",
    )
    op.drop_table("paper_fact_document_profiles")
    op.drop_index(
        op.f("ix_paper_fact_builds_collection_id"), table_name="paper_fact_builds"
    )
    op.drop_table("paper_fact_builds")
    # ### end Alembic commands ###
