"""Add build-versioned objectives

Revision ID: 20260719_0010
Revises: 20260719_0009
Create Date: 2026-07-19 23:43:56.846098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260719_0010"
down_revision: Union[str, Sequence[str], None] = "20260719_0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objective_builds",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("research_objectives_ready", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id"],
            ["collection_builds.collection_id", "collection_builds.build_id"],
            name="fk_objective_builds_collection_build",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("build_id", name=op.f("pk_objective_builds")),
        sa.UniqueConstraint(
            "collection_id", "build_id", name="uq_objective_builds_collection_build"
        ),
    )
    op.create_index(
        op.f("ix_objective_builds_collection_id"),
        "objective_builds",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "objective_paper_skims",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("skim_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("source_filename", sa.Text(), nullable=True),
        sa.Column("doc_role", sa.String(length=64), nullable=False),
        sa.Column(
            "candidate_materials",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "candidate_processes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "candidate_properties",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "changed_variables",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "possible_objectives",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("evidence_density", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_objective_paper_skims_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id"],
            ["objective_builds.collection_id", "objective_builds.build_id"],
            name="fk_objective_skims_build",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_objective_skims_source_document",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "source_document_id", name=op.f("pk_objective_paper_skims")
        ),
    )
    op.create_index(
        op.f("ix_objective_paper_skims_collection_id"),
        "objective_paper_skims",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "research_objectives",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("objective_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("objective_order", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column(
            "material_scope",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "process_axes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "property_axes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("comparison_intent", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_research_objectives_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id"],
            ["objective_builds.collection_id", "objective_builds.build_id"],
            name="fk_research_objectives_build",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "objective_id", name=op.f("pk_research_objectives")
        ),
        sa.UniqueConstraint(
            "collection_id",
            "build_id",
            "objective_id",
            name="uq_research_objectives_collection_build_objective",
        ),
    )
    op.create_index(
        op.f("ix_research_objectives_collection_id"),
        "research_objectives",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "objective_contexts",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("objective_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("context_order", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column(
            "material_scope",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "variable_process_axes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "process_context_axes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "target_property_axes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "excluded_property_axes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "objective_evidence_lens",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "routing_hints",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "extraction_guidance",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_objective_contexts_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "objective_id"],
            [
                "research_objectives.collection_id",
                "research_objectives.build_id",
                "research_objectives.objective_id",
            ],
            name="fk_objective_contexts_objective",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "objective_id", name=op.f("pk_objective_contexts")
        ),
    )
    op.create_index(
        op.f("ix_objective_contexts_collection_id"),
        "objective_contexts",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "objective_document_links",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("objective_id", sa.String(length=128), nullable=False),
        sa.Column("link_kind", sa.String(length=16), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "link_kind IN ('seed', 'excluded')",
            name=op.f("ck_objective_document_links_link_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "objective_id"],
            [
                "research_objectives.collection_id",
                "research_objectives.build_id",
                "research_objectives.objective_id",
            ],
            name="fk_objective_document_links_objective",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_objective_document_links_source",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "objective_id",
            "link_kind",
            "source_document_id",
            name=op.f("pk_objective_document_links"),
        ),
    )
    op.create_table(
        "objective_evidence_routes",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("route_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("objective_id", sa.String(length=128), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("route_order", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=128), nullable=False),
        sa.Column("source_block_id", sa.String(length=128), nullable=True),
        sa.Column("source_table_id", sa.String(length=128), nullable=True),
        sa.Column("source_figure_id", sa.String(length=128), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("extractable", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "table_schema",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "column_roles",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "join_keys",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "join_plan",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "(source_kind = 'text_window' AND source_block_id IS NOT NULL AND source_ref = source_block_id AND source_table_id IS NULL AND source_figure_id IS NULL) OR (source_kind = 'table' AND source_block_id IS NULL AND source_ref = source_table_id AND source_table_id IS NOT NULL AND source_figure_id IS NULL) OR (source_kind = 'figure' AND source_block_id IS NULL AND source_ref = source_figure_id AND source_table_id IS NULL AND source_figure_id IS NOT NULL)",
            name=op.f("ck_objective_evidence_routes_typed_source_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_objective_evidence_routes_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "objective_id"],
            [
                "research_objectives.collection_id",
                "research_objectives.build_id",
                "research_objectives.objective_id",
            ],
            name="fk_objective_routes_objective",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id", "source_block_id"],
            [
                "source_blocks.collection_id",
                "source_blocks.build_id",
                "source_blocks.source_document_id",
                "source_blocks.block_id",
            ],
            name="fk_objective_routes_block",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id", "source_figure_id"],
            [
                "source_figures.collection_id",
                "source_figures.build_id",
                "source_figures.source_document_id",
                "source_figures.figure_id",
            ],
            name="fk_objective_routes_figure",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id", "source_table_id"],
            [
                "source_tables.collection_id",
                "source_tables.build_id",
                "source_tables.source_document_id",
                "source_tables.table_id",
            ],
            name="fk_objective_routes_table",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_objective_routes_source_document",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "route_id", name=op.f("pk_objective_evidence_routes")
        ),
    )
    op.create_index(
        op.f("ix_objective_evidence_routes_collection_id"),
        "objective_evidence_routes",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "objective_evidence_units",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_unit_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("objective_id", sa.String(length=128), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("unit_order", sa.Integer(), nullable=False),
        sa.Column("unit_kind", sa.String(length=64), nullable=False),
        sa.Column("property_normalized", sa.Text(), nullable=True),
        sa.Column(
            "material_system",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "sample_context",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "process_context",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "resolved_condition",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "test_condition",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "value_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column(
            "baseline_context",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("interpretation", sa.Text(), nullable=True),
        sa.Column(
            "join_keys",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("resolution_status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_objective_evidence_units_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "objective_id"],
            [
                "research_objectives.collection_id",
                "research_objectives.build_id",
                "research_objectives.objective_id",
            ],
            name="fk_objective_units_objective",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_objective_units_source_document",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "evidence_unit_id", name=op.f("pk_objective_evidence_units")
        ),
        sa.UniqueConstraint(
            "collection_id",
            "build_id",
            "evidence_unit_id",
            name="uq_objective_units_collection_build_unit",
        ),
    )
    op.create_index(
        op.f("ix_objective_evidence_units_collection_id"),
        "objective_evidence_units",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "objective_logic_chains",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("logic_chain_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("objective_id", sa.String(length=128), nullable=False),
        sa.Column("chain_order", sa.Integer(), nullable=False),
        sa.Column("chain_scope", sa.String(length=32), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=True),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column(
            "chain_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_objective_logic_chains_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "objective_id"],
            [
                "research_objectives.collection_id",
                "research_objectives.build_id",
                "research_objectives.objective_id",
            ],
            name="fk_objective_chains_objective",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_objective_chains_source_document",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "logic_chain_id", name=op.f("pk_objective_logic_chains")
        ),
        sa.UniqueConstraint(
            "collection_id",
            "build_id",
            "logic_chain_id",
            name="uq_objective_chains_collection_build_chain",
        ),
    )
    op.create_index(
        op.f("ix_objective_logic_chains_collection_id"),
        "objective_logic_chains",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "objective_paper_frames",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("frame_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("objective_id", sa.String(length=128), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("frame_order", sa.Integer(), nullable=False),
        sa.Column("relevance", sa.String(length=32), nullable=False),
        sa.Column("paper_role", sa.String(length=64), nullable=False),
        sa.Column("background", sa.Text(), nullable=True),
        sa.Column(
            "material_match",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "changed_variables",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "measured_property_scope",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "test_environment_scope",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "relevant_sections",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "objective_id"],
            [
                "research_objectives.collection_id",
                "research_objectives.build_id",
                "research_objectives.objective_id",
            ],
            name="fk_objective_frames_objective",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id"],
            [
                "source_documents.collection_id",
                "source_documents.build_id",
                "source_documents.source_document_id",
            ],
            name="fk_objective_frames_source_document",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "frame_id", name=op.f("pk_objective_paper_frames")
        ),
        sa.UniqueConstraint(
            "collection_id",
            "build_id",
            "frame_id",
            name="uq_objective_frames_collection_build_frame",
        ),
    )
    op.create_index(
        op.f("ix_objective_paper_frames_collection_id"),
        "objective_paper_frames",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "objective_frame_table_links",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("frame_id", sa.String(length=128), nullable=False),
        sa.Column("link_kind", sa.String(length=16), nullable=False),
        sa.Column("table_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "link_kind IN ('relevant', 'excluded')",
            name=op.f("ck_objective_frame_table_links_link_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "frame_id"],
            [
                "objective_paper_frames.collection_id",
                "objective_paper_frames.build_id",
                "objective_paper_frames.frame_id",
            ],
            name="fk_objective_frame_tables_frame",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id", "table_id"],
            [
                "source_tables.collection_id",
                "source_tables.build_id",
                "source_tables.source_document_id",
                "source_tables.table_id",
            ],
            name="fk_objective_frame_tables_source",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "frame_id",
            "link_kind",
            "table_id",
            name=op.f("pk_objective_frame_table_links"),
        ),
    )
    op.create_table(
        "objective_logic_chain_unit_links",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("logic_chain_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_unit_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "evidence_unit_id"],
            [
                "objective_evidence_units.collection_id",
                "objective_evidence_units.build_id",
                "objective_evidence_units.evidence_unit_id",
            ],
            name="fk_objective_chain_units_unit",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "logic_chain_id"],
            [
                "objective_logic_chains.collection_id",
                "objective_logic_chains.build_id",
                "objective_logic_chains.logic_chain_id",
            ],
            name="fk_objective_chain_units_chain",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "logic_chain_id",
            "evidence_unit_id",
            name=op.f("pk_objective_logic_chain_unit_links"),
        ),
    )
    op.create_table(
        "objective_unit_anchor_links",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_unit_id", sa.String(length=128), nullable=False),
        sa.Column("anchor_id", sa.String(length=128), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "anchor_id"],
            [
                "paper_fact_evidence_anchors.build_id",
                "paper_fact_evidence_anchors.anchor_id",
            ],
            name="fk_objective_unit_anchors_anchor",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "evidence_unit_id"],
            [
                "objective_evidence_units.collection_id",
                "objective_evidence_units.build_id",
                "objective_evidence_units.evidence_unit_id",
            ],
            name="fk_objective_unit_anchors_unit",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "evidence_unit_id",
            "anchor_id",
            name=op.f("pk_objective_unit_anchor_links"),
        ),
    )
    op.create_table(
        "objective_unit_source_refs",
        sa.Column("build_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_unit_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=128), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=128), nullable=False),
        sa.Column("source_block_id", sa.String(length=128), nullable=True),
        sa.Column("source_table_id", sa.String(length=128), nullable=True),
        sa.Column("source_figure_id", sa.String(length=128), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source_kind = 'text_window' AND source_block_id IS NOT NULL AND source_ref = source_block_id AND source_table_id IS NULL AND source_figure_id IS NULL) OR (source_kind = 'table' AND source_block_id IS NULL AND source_ref = source_table_id AND source_table_id IS NOT NULL AND source_figure_id IS NULL) OR (source_kind = 'figure' AND source_block_id IS NULL AND source_ref = source_figure_id AND source_table_id IS NULL AND source_figure_id IS NOT NULL)",
            name=op.f("ck_objective_unit_source_refs_typed_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "evidence_unit_id"],
            [
                "objective_evidence_units.collection_id",
                "objective_evidence_units.build_id",
                "objective_evidence_units.evidence_unit_id",
            ],
            name="fk_objective_unit_refs_unit",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id", "source_block_id"],
            [
                "source_blocks.collection_id",
                "source_blocks.build_id",
                "source_blocks.source_document_id",
                "source_blocks.block_id",
            ],
            name="fk_objective_unit_refs_block",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id", "source_figure_id"],
            [
                "source_figures.collection_id",
                "source_figures.build_id",
                "source_figures.source_document_id",
                "source_figures.figure_id",
            ],
            name="fk_objective_unit_refs_figure",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "build_id", "source_document_id", "source_table_id"],
            [
                "source_tables.collection_id",
                "source_tables.build_id",
                "source_tables.source_document_id",
                "source_tables.table_id",
            ],
            name="fk_objective_unit_refs_table",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "evidence_unit_id",
            "position",
            name=op.f("pk_objective_unit_source_refs"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("objective_unit_source_refs")
    op.drop_table("objective_unit_anchor_links")
    op.drop_table("objective_logic_chain_unit_links")
    op.drop_table("objective_frame_table_links")
    op.drop_index(
        op.f("ix_objective_paper_frames_collection_id"),
        table_name="objective_paper_frames",
    )
    op.drop_table("objective_paper_frames")
    op.drop_index(
        op.f("ix_objective_logic_chains_collection_id"),
        table_name="objective_logic_chains",
    )
    op.drop_table("objective_logic_chains")
    op.drop_index(
        op.f("ix_objective_evidence_units_collection_id"),
        table_name="objective_evidence_units",
    )
    op.drop_table("objective_evidence_units")
    op.drop_index(
        op.f("ix_objective_evidence_routes_collection_id"),
        table_name="objective_evidence_routes",
    )
    op.drop_table("objective_evidence_routes")
    op.drop_table("objective_document_links")
    op.drop_index(
        op.f("ix_objective_contexts_collection_id"), table_name="objective_contexts"
    )
    op.drop_table("objective_contexts")
    op.drop_index(
        op.f("ix_research_objectives_collection_id"), table_name="research_objectives"
    )
    op.drop_table("research_objectives")
    op.drop_index(
        op.f("ix_objective_paper_skims_collection_id"),
        table_name="objective_paper_skims",
    )
    op.drop_table("objective_paper_skims")
    op.drop_index(
        op.f("ix_objective_builds_collection_id"), table_name="objective_builds"
    )
    op.drop_table("objective_builds")
    # ### end Alembic commands ###
