"""objective downstream

Revision ID: 20260720_0013
Revises: 20260720_0012
Create Date: 2026-07-20 08:22:09.340201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260720_0013'
down_revision: Union[str, Sequence[str], None] = '20260720_0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective_identity_migrations',
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('backup_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('record_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_hashes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status = 'applied'", name=op.f('ck_objective_identity_migrations_status_applied')),
    sa.CheckConstraint('length(manifest_sha256) = 64', name=op.f('ck_objective_identity_migrations_manifest_sha256_length')),
    sa.CheckConstraint('length(source_sha256) = 64', name=op.f('ck_objective_identity_migrations_source_sha256_length')),
    sa.PrimaryKeyConstraint('source_sha256', name=op.f('pk_objective_identity_migrations'))
    )
    op.create_table('objective_sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('focused_material_id', sa.String(length=128), nullable=True),
    sa.Column('focused_paper_id', sa.String(length=128), nullable=True),
    sa.Column('focused_objective_id', sa.String(length=128), nullable=True),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('intent_brief', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('answer_mode', sa.String(length=32), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=False),
    sa.Column('last_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_material_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_paper_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('collection_data_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'focused_objective_id'], ['research_objective_lifecycles.collection_id', 'research_objective_lifecycles.objective_id'], name='fk_objective_sessions_focus', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_objective_sessions_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], name=op.f('fk_objective_sessions_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_objective_sessions'))
    )
    op.create_table('research_understandings',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('source_build_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('presentation_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_traces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('content_sha256 = lower(content_sha256)', name=op.f('ck_research_understandings_content_sha256_lowercase')),
    sa.CheckConstraint('length(content_sha256) = 64', name=op.f('ck_research_understandings_content_sha256_length')),
    sa.CheckConstraint('version > 0', name=op.f('ck_research_understandings_version_positive')),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id'], ['research_objective_lifecycles.collection_id', 'research_objective_lifecycles.objective_id'], name='fk_research_understandings_objective', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', name=op.f('pk_research_understandings')),
    sa.UniqueConstraint('collection_id', 'objective_id', 'version', name='uq_research_understandings_objective_version')
    )
    op.create_index(op.f('ix_research_understandings_collection_id'), 'research_understandings', ['collection_id'], unique=False)
    op.create_index(op.f('ix_research_understandings_objective_id'), 'research_understandings', ['objective_id'], unique=False)
    op.create_table('objective_messages',
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_mode', sa.String(length=64), nullable=True),
    sa.Column('used_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review_gate', sa.String(length=64), nullable=True),
    sa.Column('source_finding_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_objective_messages_position_non_negative')),
    sa.ForeignKeyConstraint(['session_id'], ['objective_sessions.session_id'], name=op.f('fk_objective_messages_session_id_objective_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_objective_messages')),
    sa.UniqueConstraint('session_id', 'position', name='uq_objective_messages_position')
    )
    op.create_index(op.f('ix_objective_messages_session_id'), 'objective_messages', ['session_id'], unique=False)
    op.create_table('research_claims',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('claim_order', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('strength', sa.String(length=64), nullable=True),
    sa.Column('source_object_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('claim_order >= 0', name=op.f('ck_research_claims_claim_order_non_negative')),
    sa.ForeignKeyConstraint(['understanding_id'], ['research_understandings.understanding_id'], name=op.f('fk_research_claims_understanding_id_research_understandings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'claim_id', name=op.f('pk_research_claims'))
    )
    op.create_table('research_contexts',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('context_order', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('material_scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('process_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('test_condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('property_scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limitations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('context_order >= 0', name=op.f('ck_research_contexts_context_order_non_negative')),
    sa.ForeignKeyConstraint(['understanding_id'], ['research_understandings.understanding_id'], name=op.f('fk_research_contexts_understanding_id_research_understandings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'context_id', name=op.f('pk_research_contexts'))
    )
    op.create_table('research_evidence_refs',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('evidence_ref_id', sa.String(length=128), nullable=False),
    sa.Column('evidence_order', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=64), nullable=False),
    sa.Column('source_document_id', sa.String(length=128), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('locator', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fact_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('anchor_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('traceability_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_role', sa.String(length=64), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.CheckConstraint('evidence_order >= 0', name=op.f('ck_research_evidence_refs_evidence_order_non_negative')),
    sa.ForeignKeyConstraint(['understanding_id'], ['research_understandings.understanding_id'], name=op.f('fk_research_evidence_refs_understanding_id_research_understandings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'evidence_ref_id', name=op.f('pk_research_evidence_refs'))
    )
    op.create_table('research_relations',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('relation_id', sa.String(length=128), nullable=False),
    sa.Column('relation_order', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('relation_order >= 0', name=op.f('ck_research_relations_relation_order_non_negative')),
    sa.ForeignKeyConstraint(['understanding_id'], ['research_understandings.understanding_id'], name=op.f('fk_research_relations_understanding_id_research_understandings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'relation_id', name=op.f('pk_research_relations'))
    )
    op.create_table('objective_experiment_plans',
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('source_message_id', sa.String(length=128), nullable=True),
    sa.Column('source_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id'], ['research_objective_lifecycles.collection_id', 'research_objective_lifecycles.objective_id'], name='fk_objective_experiment_plans_objective', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.user_id'], name=op.f('fk_objective_experiment_plans_created_by_auth_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['objective_messages.message_id'], name=op.f('fk_objective_experiment_plans_source_message_id_objective_messages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_objective_experiment_plans'))
    )
    op.create_index(op.f('ix_objective_experiment_plans_collection_id'), 'objective_experiment_plans', ['collection_id'], unique=False)
    op.create_index(op.f('ix_objective_experiment_plans_objective_id'), 'objective_experiment_plans', ['objective_id'], unique=False)
    op.create_table('research_claim_context_links',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id', 'claim_id'], ['research_claims.understanding_id', 'research_claims.claim_id'], name=op.f('fk_research_claim_context_links_understanding_id_research_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['understanding_id', 'context_id'], ['research_contexts.understanding_id', 'research_contexts.context_id'], name=op.f('fk_research_claim_context_links_understanding_id_research_contexts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'claim_id', 'context_id', name=op.f('pk_research_claim_context_links'))
    )
    op.create_table('research_claim_evidence_links',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('evidence_ref_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id', 'claim_id'], ['research_claims.understanding_id', 'research_claims.claim_id'], name=op.f('fk_research_claim_evidence_links_understanding_id_research_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['understanding_id', 'evidence_ref_id'], ['research_evidence_refs.understanding_id', 'research_evidence_refs.evidence_ref_id'], name=op.f('fk_research_claim_evidence_links_understanding_id_research_evidence_refs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'claim_id', 'evidence_ref_id', name=op.f('pk_research_claim_evidence_links'))
    )
    op.create_table('research_findings',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('finding_order', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.String(length=64), nullable=True),
    sa.Column('evidence_ref_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('finding_order >= 0', name=op.f('ck_research_findings_finding_order_non_negative')),
    sa.ForeignKeyConstraint(['understanding_id', 'claim_id'], ['research_claims.understanding_id', 'research_claims.claim_id'], name='fk_research_findings_claim', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'finding_id', name=op.f('pk_research_findings'))
    )
    op.create_table('research_relation_context_links',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('relation_id', sa.String(length=128), nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id', 'context_id'], ['research_contexts.understanding_id', 'research_contexts.context_id'], name=op.f('fk_research_relation_context_links_understanding_id_research_contexts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['understanding_id', 'relation_id'], ['research_relations.understanding_id', 'research_relations.relation_id'], name=op.f('fk_research_relation_context_links_understanding_id_research_relations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'relation_id', 'context_id', name=op.f('pk_research_relation_context_links'))
    )
    op.create_table('research_relation_evidence_links',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('relation_id', sa.String(length=128), nullable=False),
    sa.Column('evidence_ref_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id', 'evidence_ref_id'], ['research_evidence_refs.understanding_id', 'research_evidence_refs.evidence_ref_id'], name=op.f('fk_research_relation_evidence_links_understanding_id_research_evidence_refs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['understanding_id', 'relation_id'], ['research_relations.understanding_id', 'research_relations.relation_id'], name=op.f('fk_research_relation_evidence_links_understanding_id_research_relations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'relation_id', 'evidence_ref_id', 'role', name=op.f('pk_research_relation_evidence_links'))
    )
    op.create_table('research_finding_evidence_links',
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=False),
    sa.Column('evidence_ref_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id', 'evidence_ref_id'], ['research_evidence_refs.understanding_id', 'research_evidence_refs.evidence_ref_id'], name=op.f('fk_research_finding_evidence_links_understanding_id_research_evidence_refs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['understanding_id', 'finding_id'], ['research_findings.understanding_id', 'research_findings.finding_id'], name=op.f('fk_research_finding_evidence_links_understanding_id_research_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('understanding_id', 'finding_id', 'evidence_ref_id', name=op.f('pk_research_finding_evidence_links'))
    )
    op.create_table('research_understanding_curation_records',
    sa.Column('curation_id', sa.String(length=128), nullable=False),
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=True),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('finding_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('curated_claim_type', sa.String(length=64), nullable=False),
    sa.Column('curated_status', sa.String(length=64), nullable=False),
    sa.Column('curated_statement', sa.Text(), nullable=False),
    sa.Column('curated_support_grade', sa.String(length=64), nullable=True),
    sa.Column('curated_review_status', sa.String(length=64), nullable=True),
    sa.Column('curated_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('curated_mediators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('curated_outcomes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('curated_direction', sa.String(length=64), nullable=True),
    sa.Column('curated_scope_summary', sa.Text(), nullable=True),
    sa.Column('curated_evidence_ref_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('curated_context_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id', 'claim_id'], ['research_claims.understanding_id', 'research_claims.claim_id'], name='fk_understanding_curations_claim', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['understanding_id', 'finding_id'], ['research_findings.understanding_id', 'research_findings.finding_id'], name='fk_understanding_curations_finding', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curation_id', name=op.f('pk_research_understanding_curation_records'))
    )
    op.create_index(op.f('ix_research_understanding_curation_records_collection_id'), 'research_understanding_curation_records', ['collection_id'], unique=False)
    op.create_index(op.f('ix_research_understanding_curation_records_objective_id'), 'research_understanding_curation_records', ['objective_id'], unique=False)
    op.create_table('research_understanding_feedback_records',
    sa.Column('feedback_id', sa.String(length=128), nullable=False),
    sa.Column('understanding_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=True),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('finding_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id', 'claim_id'], ['research_claims.understanding_id', 'research_claims.claim_id'], name='fk_understanding_feedback_claim', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['understanding_id', 'finding_id'], ['research_findings.understanding_id', 'research_findings.finding_id'], name='fk_understanding_feedback_finding', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('pk_research_understanding_feedback_records'))
    )
    op.create_index(op.f('ix_research_understanding_feedback_records_collection_id'), 'research_understanding_feedback_records', ['collection_id'], unique=False)
    op.create_index(op.f('ix_research_understanding_feedback_records_objective_id'), 'research_understanding_feedback_records', ['objective_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_understanding_feedback_records_objective_id'), table_name='research_understanding_feedback_records')
    op.drop_index(op.f('ix_research_understanding_feedback_records_collection_id'), table_name='research_understanding_feedback_records')
    op.drop_table('research_understanding_feedback_records')
    op.drop_index(op.f('ix_research_understanding_curation_records_objective_id'), table_name='research_understanding_curation_records')
    op.drop_index(op.f('ix_research_understanding_curation_records_collection_id'), table_name='research_understanding_curation_records')
    op.drop_table('research_understanding_curation_records')
    op.drop_table('research_finding_evidence_links')
    op.drop_table('research_relation_evidence_links')
    op.drop_table('research_relation_context_links')
    op.drop_table('research_findings')
    op.drop_table('research_claim_evidence_links')
    op.drop_table('research_claim_context_links')
    op.drop_index(op.f('ix_objective_experiment_plans_objective_id'), table_name='objective_experiment_plans')
    op.drop_index(op.f('ix_objective_experiment_plans_collection_id'), table_name='objective_experiment_plans')
    op.drop_table('objective_experiment_plans')
    op.drop_table('research_relations')
    op.drop_table('research_evidence_refs')
    op.drop_table('research_contexts')
    op.drop_table('research_claims')
    op.drop_index(op.f('ix_objective_messages_session_id'), table_name='objective_messages')
    op.drop_table('objective_messages')
    op.drop_index(op.f('ix_research_understandings_objective_id'), table_name='research_understandings')
    op.drop_index(op.f('ix_research_understandings_collection_id'), table_name='research_understandings')
    op.drop_table('research_understandings')
    op.drop_table('objective_sessions')
    op.drop_table('objective_identity_migrations')
    # ### end Alembic commands ###
