"""current schema baseline

Revision ID: 20260828_0001
Revises:
Create Date: 2026-08-28 14:36:07.734439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260828_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_auth_users_email_normalized')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_auth_users')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_users_email'))
    )
    op.create_table('objective_discovery',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('research_objectives_ready', sa.Boolean(), nullable=False),
    sa.Column('document_inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('objective_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('study_dispositions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('collection_id', name=op.f('pk_objective_discovery'))
    )
    op.create_table('research_objectives',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('created_by_tool_call_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('collection_id', 'objective_id', name=op.f('pk_research_objectives')),
    sa.UniqueConstraint('created_by_tool_call_id', name='uq_research_objectives_created_by_tool_call')
    )
    op.create_table('source_reference_candidates',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('cited_by_document_id', sa.String(length=128), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('representative_context', sa.Text(), nullable=True),
    sa.Column('resolved_doi', sa.Text(), nullable=True),
    sa.Column('resolved_url', sa.Text(), nullable=True),
    sa.Column('open_access_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('mention_count >= 0', name=op.f('ck_source_reference_candidates_mention_count_non_negative')),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_source_reference_candidates_relevance_score_range')),
    sa.PrimaryKeyConstraint('candidate_id', name=op.f('pk_source_reference_candidates'))
    )
    op.create_index(op.f('ix_source_reference_candidates_reference_id'), 'source_reference_candidates', ['reference_id'], unique=False)
    op.create_table('source_reference_resolutions',
    sa.Column('resolution_id', sa.String(length=128), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('resolved_title', sa.Text(), nullable=True),
    sa.Column('resolved_authors_text', sa.Text(), nullable=True),
    sa.Column('resolved_year', sa.Integer(), nullable=True),
    sa.Column('resolved_venue', sa.Text(), nullable=True),
    sa.Column('resolved_doi', sa.Text(), nullable=True),
    sa.Column('resolved_url', sa.Text(), nullable=True),
    sa.Column('open_access_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_source_reference_resolutions_confidence_range')),
    sa.CheckConstraint('resolved_year IS NULL OR resolved_year >= 0', name=op.f('ck_source_reference_resolutions_resolved_year_non_negative')),
    sa.PrimaryKeyConstraint('resolution_id', name=op.f('pk_source_reference_resolutions'))
    )
    op.create_index(op.f('ix_source_reference_resolutions_reference_id'), 'source_reference_resolutions', ['reference_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_auth_sessions_valid_expiry')),
    sa.CheckConstraint('length(token_hash) = 64', name=op.f('ck_auth_sessions_token_hash_length')),
    sa.CheckConstraint('token_hash = lower(token_hash)', name=op.f('ck_auth_sessions_token_hash_lowercase')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], name=op.f('fk_auth_sessions_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('paper_count >= 0', name=op.f('ck_collections_paper_count_non_negative')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_collections_valid_timestamps')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.user_id'], name=op.f('fk_collections_owner_user_id_auth_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('collection_id', name=op.f('pk_collections'))
    )
    op.create_index(op.f('ix_collections_owner_user_id'), 'collections', ['owner_user_id'], unique=False)
    op.create_table('objective_analyses',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id'], ['research_objectives.collection_id', 'research_objectives.objective_id'], name='fk_objective_analyses_objective', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'objective_id', 'analysis_version', name=op.f('pk_objective_analyses'))
    )
    op.create_index(op.f('ix_objective_analyses_status'), 'objective_analyses', ['status'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_chat_sessions_valid_timestamps')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_chat_sessions_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], name=op.f('fk_chat_sessions_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_collection_id'), 'chat_sessions', ['collection_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('stored_filename', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('document_order', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=128), nullable=True),
    sa.Column('document_analysis_version', sa.String(length=128), nullable=True),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('profile_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('preparation_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('document_order >= 0', name=op.f('ck_documents_document_order_non_negative')),
    sa.CheckConstraint('length(sha256) = 64', name=op.f('ck_documents_sha256_length')),
    sa.CheckConstraint('sha256 = lower(sha256)', name=op.f('ck_documents_sha256_lowercase')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_documents_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_documents_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_documents')),
    sa.UniqueConstraint('collection_id', 'document_order', name='uq_documents_collection_order'),
    sa.UniqueConstraint('collection_id', 'sha256', name='uq_documents_collection_content'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index(op.f('ix_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_table('evaluation_gold_sets',
    sa.Column('gold_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('target_layer', sa.String(length=32), nullable=False),
    sa.Column('metric_profile', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_evaluation_gold_sets_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gold_id', name=op.f('pk_evaluation_gold_sets'))
    )
    op.create_index(op.f('ix_evaluation_gold_sets_collection_id'), 'evaluation_gold_sets', ['collection_id'], unique=False)
    op.create_table('evaluation_prediction_snapshots',
    sa.Column('snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('target_layer', sa.String(length=32), nullable=False),
    sa.Column('fact_source', sa.String(length=64), nullable=False),
    sa.Column('system_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_evaluation_prediction_snapshots_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_evaluation_prediction_snapshots'))
    )
    op.create_index('ix_evaluation_snapshots_collection', 'evaluation_prediction_snapshots', ['collection_id', 'fact_source'], unique=False)
    op.create_table('objective_findings',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=False),
    sa.Column('display_rank', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id', 'analysis_version'], ['objective_analyses.collection_id', 'objective_analyses.objective_id', 'objective_analyses.analysis_version'], name='fk_objective_findings_analysis', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'objective_id', 'analysis_version', 'finding_id', name=op.f('pk_objective_findings'))
    )
    op.create_table('objective_paper_contributions',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id', 'analysis_version'], ['objective_analyses.collection_id', 'objective_analyses.objective_id', 'objective_analyses.analysis_version'], name='fk_objective_contributions_analysis', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'objective_id', 'analysis_version', 'source_document_id', name=op.f('pk_objective_paper_contributions'))
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=128), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('tool_arguments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'tool')", name=op.f('ck_chat_messages_role_valid')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_chat_messages_position_non_negative')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_chat_messages')),
    sa.UniqueConstraint('session_id', 'position', name='uq_chat_messages_position')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('document_profiles',
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('parsing_warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_document_profiles_confidence_range')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_document_profiles_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_document_profiles_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document_profiles'))
    )
    op.create_index(op.f('ix_document_profiles_collection_id'), 'document_profiles', ['collection_id'], unique=False)
    op.create_table('evaluation_gold_items',
    sa.Column('gold_item_id', sa.String(length=128), nullable=False),
    sa.Column('gold_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=128), nullable=False),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['gold_id'], ['evaluation_gold_sets.gold_id'], name=op.f('fk_evaluation_gold_items_gold_id_evaluation_gold_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gold_item_id', name=op.f('pk_evaluation_gold_items'))
    )
    op.create_index('ix_evaluation_gold_items_gold_family', 'evaluation_gold_items', ['gold_id', 'family', 'document_id'], unique=False)
    op.create_table('evaluation_prediction_items',
    sa.Column('snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=128), nullable=False),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evaluation_prediction_snapshots.snapshot_id'], name=op.f('fk_evaluation_prediction_items_snapshot_id_evaluation_prediction_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'item_id', name=op.f('pk_evaluation_prediction_items'))
    )
    op.create_index('ix_evaluation_prediction_items_family', 'evaluation_prediction_items', ['snapshot_id', 'family', 'document_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('evaluation_run_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('gold_id', sa.String(length=128), nullable=False),
    sa.Column('prediction_snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('target_layer', sa.String(length=32), nullable=False),
    sa.Column('fact_source', sa.String(length=64), nullable=False),
    sa.Column('metric_profile', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_evaluation_runs_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gold_id'], ['evaluation_gold_sets.gold_id'], name=op.f('fk_evaluation_runs_gold_id_evaluation_gold_sets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prediction_snapshot_id'], ['evaluation_prediction_snapshots.snapshot_id'], name=op.f('fk_evaluation_runs_prediction_snapshot_id_evaluation_prediction_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evaluation_run_id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index('ix_evaluation_runs_collection', 'evaluation_runs', ['collection_id', 'created_at'], unique=False)
    op.create_table('finding_curation_records',
    sa.Column('curation_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=False),
    sa.Column('curated_status', sa.String(length=64), nullable=False),
    sa.Column('curated_finding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id', 'analysis_version', 'finding_id'], ['objective_findings.collection_id', 'objective_findings.objective_id', 'objective_findings.analysis_version', 'objective_findings.finding_id'], name='fk_finding_curations_finding', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curation_id', name=op.f('pk_finding_curation_records'))
    )
    op.create_index(op.f('ix_finding_curation_records_collection_id'), 'finding_curation_records', ['collection_id'], unique=False)
    op.create_index(op.f('ix_finding_curation_records_objective_id'), 'finding_curation_records', ['objective_id'], unique=False)
    op.create_table('finding_feedback_records',
    sa.Column('feedback_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=False),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id', 'analysis_version', 'finding_id'], ['objective_findings.collection_id', 'objective_findings.objective_id', 'objective_findings.analysis_version', 'objective_findings.finding_id'], name='fk_finding_feedback_finding', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('pk_finding_feedback_records'))
    )
    op.create_index(op.f('ix_finding_feedback_records_collection_id'), 'finding_feedback_records', ['collection_id'], unique=False)
    op.create_index(op.f('ix_finding_feedback_records_objective_id'), 'finding_feedback_records', ['objective_id'], unique=False)
    op.create_table('objective_document_evidence_checkpoints',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id'], ['research_objectives.collection_id', 'research_objectives.objective_id'], name='fk_objective_document_evidence_objective', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='fk_objective_document_evidence_document', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'objective_id', 'document_id', 'input_fingerprint', name=op.f('pk_objective_document_evidence_checkpoints'))
    )
    op.create_index(op.f('ix_objective_document_evidence_checkpoints_status'), 'objective_document_evidence_checkpoints', ['status'], unique=False)
    op.create_table('objective_evidence',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id', 'analysis_version', 'source_document_id'], ['objective_paper_contributions.collection_id', 'objective_paper_contributions.objective_id', 'objective_paper_contributions.analysis_version', 'objective_paper_contributions.source_document_id'], name='fk_objective_evidence_contribution', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id', 'analysis_version'], ['objective_analyses.collection_id', 'objective_analyses.objective_id', 'objective_analyses.analysis_version'], name='fk_objective_evidence_analysis', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'objective_id', 'analysis_version', 'evidence_id', name=op.f('pk_objective_evidence'))
    )
    op.create_table('paper_maps',
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_paper_maps_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_paper_maps_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_paper_maps'))
    )
    op.create_index(op.f('ix_paper_maps_collection_id'), 'paper_maps', ['collection_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('document_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('document_order >= 0', name=op.f('ck_source_documents_document_order_non_negative')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_source_documents_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.document_id'], name=op.f('fk_source_documents_source_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', name=op.f('pk_source_documents'))
    )
    op.create_index(op.f('ix_source_documents_collection_id'), 'source_documents', ['collection_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=128), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("current_stage <> ''", name=op.f('ck_tasks_current_stage_not_empty')),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'partial_success', 'failed')", name=op.f('ck_tasks_valid_status')),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= created_at', name=op.f('ck_tasks_valid_finished_at')),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name=op.f('ck_tasks_valid_progress_percent')),
    sa.CheckConstraint('started_at IS NULL OR started_at >= created_at', name=op.f('ck_tasks_valid_started_at')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_tasks_valid_timestamps')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name=op.f('fk_tasks_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_tasks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_collection_id'), 'tasks', ['collection_id'], unique=False)
    op.create_index(op.f('ix_tasks_document_id'), 'tasks', ['document_id'], unique=False)
    op.create_index('uq_tasks_active_document_type', 'tasks', ['document_id', 'task_type'], unique=True, postgresql_where=sa.text("document_id IS NOT NULL AND status IN ('queued', 'running')"), sqlite_where=sa.text("document_id IS NOT NULL AND status IN ('queued', 'running')"))
    op.create_table('chat_tool_calls',
    sa.Column('tool_call_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('assistant_message_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('arguments_digest', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('decision_user_id', sa.String(length=64), nullable=True),
    sa.Column('decision_arguments_digest', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("risk IN ('unknown', 'read', 'draft', 'write')", name=op.f('ck_chat_tool_calls_risk_valid')),
    sa.CheckConstraint("status IN ('requested', 'approval_required', 'approved', 'running', 'succeeded', 'failed', 'rejected')", name=op.f('ck_chat_tool_calls_status_valid')),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['chat_messages.message_id'], name=op.f('fk_chat_tool_calls_assistant_message_id_chat_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_user_id'], ['auth_users.user_id'], name=op.f('fk_chat_tool_calls_decision_user_id_auth_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name=op.f('fk_chat_tool_calls_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id', name=op.f('pk_chat_tool_calls')),
    sa.UniqueConstraint('assistant_message_id', name='uq_chat_tool_calls_assistant_message')
    )
    op.create_index(op.f('ix_chat_tool_calls_session_id'), 'chat_tool_calls', ['session_id'], unique=False)
    op.create_table('evaluation_failures',
    sa.Column('failure_id', sa.String(length=128), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=128), nullable=False),
    sa.Column('failure_type', sa.String(length=64), nullable=False),
    sa.Column('likely_layer', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('gold_item_id', sa.String(length=128), nullable=True),
    sa.Column('prediction_item_id', sa.String(length=128), nullable=True),
    sa.Column('gold', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('prediction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.evaluation_run_id'], name=op.f('fk_evaluation_failures_evaluation_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('failure_id', name=op.f('pk_evaluation_failures'))
    )
    op.create_index('ix_evaluation_failures_family', 'evaluation_failures', ['evaluation_run_id', 'family', 'failure_type'], unique=False)
    op.create_table('evaluation_scores',
    sa.Column('score_id', sa.String(length=128), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=True),
    sa.Column('family', sa.String(length=128), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('numerator', sa.Float(), nullable=True),
    sa.Column('denominator', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.evaluation_run_id'], name=op.f('fk_evaluation_scores_evaluation_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id', name=op.f('pk_evaluation_scores'))
    )
    op.create_index(op.f('ix_evaluation_scores_evaluation_run_id'), 'evaluation_scores', ['evaluation_run_id'], unique=False)
    op.create_table('objective_experiment_plans',
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('objective_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('source_message_id', sa.String(length=128), nullable=True),
    sa.Column('source_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'objective_id'], ['research_objectives.collection_id', 'research_objectives.objective_id'], name='fk_objective_experiment_plans_objective', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.user_id'], name=op.f('fk_objective_experiment_plans_created_by_auth_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.message_id'], name='fk_objective_experiment_plans_source_message_id_chat_messages', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_objective_experiment_plans'))
    )
    op.create_index(op.f('ix_objective_experiment_plans_collection_id'), 'objective_experiment_plans', ['collection_id'], unique=False)
    op.create_index(op.f('ix_objective_experiment_plans_objective_id'), 'objective_experiment_plans', ['objective_id'], unique=False)
    op.create_table('source_blocks',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('block_type', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.CheckConstraint('block_order >= 0', name=op.f('ck_source_blocks_block_order_non_negative')),
    sa.CheckConstraint('page IS NULL OR page >= 0', name=op.f('ck_source_blocks_page_non_negative')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.source_document_id'], name=op.f('fk_source_blocks_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'block_id', name=op.f('pk_source_blocks'))
    )
    op.create_table('source_figures',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('figure_id', sa.String(length=128), nullable=False),
    sa.Column('figure_order', sa.Integer(), nullable=False),
    sa.Column('figure_label', sa.Text(), nullable=True),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('caption_block_id', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('image_storage_key', sa.Text(), nullable=True),
    sa.Column('image_mime_type', sa.String(length=255), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('asset_sha256', sa.String(length=64), nullable=True),
    sa.Column('image_size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('(image_storage_key IS NULL AND asset_sha256 IS NULL AND image_size_bytes IS NULL) OR (image_storage_key IS NOT NULL AND asset_sha256 IS NOT NULL AND image_size_bytes IS NOT NULL)', name=op.f('ck_source_figures_image_object_complete')),
    sa.CheckConstraint('figure_order >= 0', name=op.f('ck_source_figures_figure_order_non_negative')),
    sa.CheckConstraint('image_height IS NULL OR image_height >= 0', name=op.f('ck_source_figures_image_height_non_negative')),
    sa.CheckConstraint('image_size_bytes IS NULL OR image_size_bytes >= 0', name=op.f('ck_source_figures_image_size_bytes_non_negative')),
    sa.CheckConstraint('image_width IS NULL OR image_width >= 0', name=op.f('ck_source_figures_image_width_non_negative')),
    sa.CheckConstraint('page IS NULL OR page >= 0', name=op.f('ck_source_figures_page_non_negative')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.source_document_id'], name=op.f('fk_source_figures_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'figure_id', name=op.f('pk_source_figures'))
    )
    op.create_table('source_reference_entries',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('raw_reference', sa.Text(), nullable=False),
    sa.Column('reference_index', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors_text', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('source_block_id', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_source_reference_entries_confidence_range')),
    sa.CheckConstraint('page IS NULL OR page >= 0', name=op.f('ck_source_reference_entries_page_non_negative')),
    sa.CheckConstraint('year IS NULL OR year >= 0', name=op.f('ck_source_reference_entries_year_non_negative')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.source_document_id'], name=op.f('fk_source_reference_entries_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'reference_id', name=op.f('pk_source_reference_entries'))
    )
    op.create_table('source_reference_mentions',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('mention_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('citation_marker', sa.Text(), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=False),
    sa.Column('source_block_id', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_source_reference_mentions_confidence_range')),
    sa.CheckConstraint('page IS NULL OR page >= 0', name=op.f('ck_source_reference_mentions_page_non_negative')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.source_document_id'], name=op.f('fk_source_reference_mentions_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'mention_id', name=op.f('pk_source_reference_mentions'))
    )
    op.create_table('source_tables',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('table_order', sa.Integer(), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('caption_block_id', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('header_row_count', sa.Integer(), nullable=False),
    sa.Column('column_headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('table_matrix', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('header_row_count >= 0', name=op.f('ck_source_tables_header_row_count_non_negative')),
    sa.CheckConstraint('page IS NULL OR page >= 0', name=op.f('ck_source_tables_page_non_negative')),
    sa.CheckConstraint('table_order >= 0', name=op.f('ck_source_tables_table_order_non_negative')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.source_document_id'], name=op.f('fk_source_tables_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'table_id', name=op.f('pk_source_tables'))
    )
    op.create_table('source_text_units',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('text_unit_id', sa.String(length=128), nullable=False),
    sa.Column('text_unit_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('n_tokens', sa.Integer(), nullable=True),
    sa.CheckConstraint('n_tokens IS NULL OR n_tokens >= 0', name=op.f('ck_source_text_units_n_tokens_non_negative')),
    sa.CheckConstraint('text_unit_order >= 0', name=op.f('ck_source_text_units_text_unit_order_non_negative')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.source_document_id'], name=op.f('fk_source_text_units_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'text_unit_id', name=op.f('pk_source_text_units'))
    )
    op.create_table('task_stages',
    sa.Column('stage_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('stage_kind', sa.String(length=128), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dependencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("stage_kind <> ''", name=op.f('ck_task_stages_stage_kind_not_empty')),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'skipped')", name=op.f('ck_task_stages_valid_status')),
    sa.CheckConstraint('stage_order >= 0', name=op.f('ck_task_stages_stage_order_non_negative')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_task_stages_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stage_id', name=op.f('pk_task_stages')),
    sa.UniqueConstraint('task_id', 'stage_kind', name='uq_task_stages_task_kind'),
    sa.UniqueConstraint('task_id', 'stage_order', name='uq_task_stages_task_order')
    )
    op.create_index(op.f('ix_task_stages_task_id'), 'task_stages', ['task_id'], unique=False)
    op.create_table('chat_tool_results',
    sa.Column('tool_call_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resource_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('succeeded', 'queued', 'failed')", name=op.f('ck_chat_tool_results_status_valid')),
    sa.ForeignKeyConstraint(['tool_call_id'], ['chat_tool_calls.tool_call_id'], name=op.f('fk_chat_tool_results_tool_call_id_chat_tool_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id', name=op.f('pk_chat_tool_results'))
    )
    op.create_table('source_block_text_units',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('text_unit_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id', 'block_id'], ['source_blocks.source_document_id', 'source_blocks.block_id'], name=op.f('fk_source_block_text_units_source_document_id_source_blocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id', 'text_unit_id'], ['source_text_units.source_document_id', 'source_text_units.text_unit_id'], name=op.f('fk_source_block_text_units_source_document_id_source_text_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'block_id', 'text_unit_id', name=op.f('pk_source_block_text_units'))
    )
    op.create_table('source_table_cells',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('cell_id', sa.String(length=128), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('cell_text', sa.Text(), nullable=False),
    sa.Column('row_span', sa.Integer(), nullable=False),
    sa.Column('col_span', sa.Integer(), nullable=False),
    sa.Column('column_header', sa.Boolean(), nullable=False),
    sa.Column('row_header', sa.Boolean(), nullable=False),
    sa.Column('row_section', sa.Boolean(), nullable=False),
    sa.Column('header_path', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('unit_hint', sa.Text(), nullable=True),
    sa.CheckConstraint('col_index >= 0', name=op.f('ck_source_table_cells_col_index_non_negative')),
    sa.CheckConstraint('col_span >= 1', name=op.f('ck_source_table_cells_col_span_positive')),
    sa.CheckConstraint('page IS NULL OR page >= 0', name=op.f('ck_source_table_cells_page_non_negative')),
    sa.CheckConstraint('row_index >= 0', name=op.f('ck_source_table_cells_row_index_non_negative')),
    sa.CheckConstraint('row_span >= 1', name=op.f('ck_source_table_cells_row_span_positive')),
    sa.ForeignKeyConstraint(['source_document_id', 'table_id'], ['source_tables.source_document_id', 'source_tables.table_id'], name=op.f('fk_source_table_cells_source_document_id_source_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'cell_id', name=op.f('pk_source_table_cells'))
    )
    op.create_table('source_table_rows',
    sa.Column('source_document_id', sa.String(length=128), nullable=False),
    sa.Column('row_id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('row_text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.CheckConstraint('page IS NULL OR page >= 0', name=op.f('ck_source_table_rows_page_non_negative')),
    sa.CheckConstraint('row_index >= 0', name=op.f('ck_source_table_rows_row_index_non_negative')),
    sa.ForeignKeyConstraint(['source_document_id', 'table_id'], ['source_tables.source_document_id', 'source_tables.table_id'], name=op.f('fk_source_table_rows_source_document_id_source_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_document_id', 'row_id', name=op.f('pk_source_table_rows'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_table_rows')
    op.drop_table('source_table_cells')
    op.drop_table('source_block_text_units')
    op.drop_table('chat_tool_results')
    op.drop_index(op.f('ix_task_stages_task_id'), table_name='task_stages')
    op.drop_table('task_stages')
    op.drop_table('source_text_units')
    op.drop_table('source_tables')
    op.drop_table('source_reference_mentions')
    op.drop_table('source_reference_entries')
    op.drop_table('source_figures')
    op.drop_table('source_blocks')
    op.drop_index(op.f('ix_objective_experiment_plans_objective_id'), table_name='objective_experiment_plans')
    op.drop_index(op.f('ix_objective_experiment_plans_collection_id'), table_name='objective_experiment_plans')
    op.drop_table('objective_experiment_plans')
    op.drop_index(op.f('ix_evaluation_scores_evaluation_run_id'), table_name='evaluation_scores')
    op.drop_table('evaluation_scores')
    op.drop_index('ix_evaluation_failures_family', table_name='evaluation_failures')
    op.drop_table('evaluation_failures')
    op.drop_index(op.f('ix_chat_tool_calls_session_id'), table_name='chat_tool_calls')
    op.drop_table('chat_tool_calls')
    op.drop_index('uq_tasks_active_document_type', table_name='tasks', postgresql_where=sa.text("document_id IS NOT NULL AND status IN ('queued', 'running')"), sqlite_where=sa.text("document_id IS NOT NULL AND status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_tasks_document_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_collection_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_source_documents_collection_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_paper_maps_collection_id'), table_name='paper_maps')
    op.drop_table('paper_maps')
    op.drop_table('objective_evidence')
    op.drop_index(op.f('ix_objective_document_evidence_checkpoints_status'), table_name='objective_document_evidence_checkpoints')
    op.drop_table('objective_document_evidence_checkpoints')
    op.drop_index(op.f('ix_finding_feedback_records_objective_id'), table_name='finding_feedback_records')
    op.drop_index(op.f('ix_finding_feedback_records_collection_id'), table_name='finding_feedback_records')
    op.drop_table('finding_feedback_records')
    op.drop_index(op.f('ix_finding_curation_records_objective_id'), table_name='finding_curation_records')
    op.drop_index(op.f('ix_finding_curation_records_collection_id'), table_name='finding_curation_records')
    op.drop_table('finding_curation_records')
    op.drop_index('ix_evaluation_runs_collection', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('ix_evaluation_prediction_items_family', table_name='evaluation_prediction_items')
    op.drop_table('evaluation_prediction_items')
    op.drop_index('ix_evaluation_gold_items_gold_family', table_name='evaluation_gold_items')
    op.drop_table('evaluation_gold_items')
    op.drop_index(op.f('ix_document_profiles_collection_id'), table_name='document_profiles')
    op.drop_table('document_profiles')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('objective_paper_contributions')
    op.drop_table('objective_findings')
    op.drop_index('ix_evaluation_snapshots_collection', table_name='evaluation_prediction_snapshots')
    op.drop_table('evaluation_prediction_snapshots')
    op.drop_index(op.f('ix_evaluation_gold_sets_collection_id'), table_name='evaluation_gold_sets')
    op.drop_table('evaluation_gold_sets')
    op.drop_index(op.f('ix_documents_collection_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_collection_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_objective_analyses_status'), table_name='objective_analyses')
    op.drop_table('objective_analyses')
    op.drop_index(op.f('ix_collections_owner_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_source_reference_resolutions_reference_id'), table_name='source_reference_resolutions')
    op.drop_table('source_reference_resolutions')
    op.drop_index(op.f('ix_source_reference_candidates_reference_id'), table_name='source_reference_candidates')
    op.drop_table('source_reference_candidates')
    op.drop_table('research_objectives')
    op.drop_table('objective_discovery')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
