"""Source-domain records and status semantics."""

from domain.source.artifact_status import ArtifactStatusRecord
from domain.source.artifacts import (
    SourceBlock,
    SourceBlockType,
    SourceArtifactSet,
    SourceBoundingBox,
    SourceCharRange,
    SourceDocument,
    SourceFigure,
    SourceLayoutBlock,
    SourceTable,
    SourceTableCell,
    SourceTableRow,
    SourceTextUnit,
    build_figure_caption_blocks,
    build_heading_blocks,
    build_source_table_rows_from_cells,
    build_table_caption_blocks,
    extract_unit_hint,
    find_nearest_caption_block,
    first_non_null,
    make_table_id,
    normalize_optional_text,
    render_markdown_table,
    render_plain_table_text,
    resolve_heading_path_for_page,
    resolve_heading_path_for_target,
    safe_int,
    update_heading_stack,
)
from domain.source.collection import CollectionRecord, empty_import_manifest

__all__ = [
    "ArtifactStatusRecord",
    "CollectionRecord",
    "SourceBlock",
    "SourceBlockType",
    "SourceArtifactSet",
    "SourceBoundingBox",
    "SourceCharRange",
    "SourceDocument",
    "SourceFigure",
    "SourceLayoutBlock",
    "SourceTable",
    "SourceTableCell",
    "SourceTableRow",
    "SourceTextUnit",
    "build_figure_caption_blocks",
    "build_heading_blocks",
    "build_source_table_rows_from_cells",
    "build_table_caption_blocks",
    "empty_import_manifest",
    "extract_unit_hint",
    "find_nearest_caption_block",
    "first_non_null",
    "make_table_id",
    "normalize_optional_text",
    "render_markdown_table",
    "render_plain_table_text",
    "resolve_heading_path_for_page",
    "resolve_heading_path_for_target",
    "safe_int",
    "update_heading_stack",
]
